### ISSUE TITLE
file_name or fileName

### ISSUE THREAD

**Issue by jeroen-3dweb** [buttonizer/freemius-deploy#1] opened 2020-09-06 21:31 UTC
Hello,

In your example you use the argument file_name.

_- name: Deploy to Freemius
  uses: buttonizer/freemius-deploy@v0.1.1
  with:
    **file_name**: my_wordpress_plugin.zip
    release_mode: pending
    version: 1.1.0
    sandbox: false_

But when I use that I get the warning below:
Unexpected input(s) 'file_name', valid inputs are ['entryPoint', 'args', 'sandbox', 'fileName', 'version', 'releaseMode']

But it works but later on I get the error         (
            [type] => InvalidArgument
            [message] => Your module's readme.txt file is missing.
            [code] => readme_missing
            [http] => 400
            [timestamp] => Sun, 06 Sep 2020 21:11:07 +0000
        )

When I manually upload the zip to Freemius it is accepted. I know these are 2 seperated issues but maybe they are connected if it's not uploading anything.

**Comment by castorverhoog** [comment] 2020-09-08 10:43
Hi, thanks for reporting this! The first part of the issue I have fixed locally and will deploy in a new version today.
The second part of the issue is about the readme.txt missing. I have reproduced it at my end, but when I have no readme.txt, deployment also doesn't work in the freemius dashboard, just like the API refuses it. Is it true you have no readme.txt?

**Comment by jeroen-3dweb** [comment] 2020-09-08 11:10
yes, it was my mistake. I 've created a zip file from a subdirectory but it took the whole path in it. I first had to copy everything to the root before zipping it. For the first part the quick and dirty solution I did for now whas to put  INPUT_FILE_NAME: 360-jsv.zip into the env section.

**Comment by castorverhoog** [comment] 2020-09-08 11:32
I have released v0.1.2 with the fix for this issue.

**Closed as completed by castorverhoog** 2020-09-08 11:32 UTC
